export const RPC_METHODS = {
    Permission: 'permission',
    Abort: 'abort',
    Switch: 'switch',
    SetSessionConfig: 'set-session-config',
    KillSession: 'killSession',
    HandoffLocal: 'handoff-local',
    SpawnHappySession: 'spawn-happy-session',
    StopSession: 'stop-session',
    StopRunner: 'stop-runner',
    ListCodexLocalSessions: 'listCodexLocalSessions',
    ReadCodexLocalSession: 'readCodexLocalSession',
    GetCodexLocalSessionStatus: 'getCodexLocalSessionStatus',
    SendCodexLocalSessionMessage: 'sendCodexLocalSessionMessage',
    ListMachineDirectory: 'list-directory',
    PathExists: 'path-exists',
    GitStatus: 'git-status',
    GitDiffNumstat: 'git-diff-numstat',
    GitDiffFile: 'git-diff-file',
    ReadFile: 'readFile',
    ReadGeneratedImage: 'readGeneratedImage',
    WriteFile: 'writeFile',
    ListDirectory: 'listDirectory',
    GetDirectoryTree: 'getDirectoryTree',
    UploadFile: 'uploadFile',
    DeleteUpload: 'deleteUpload',
    Ripgrep: 'ripgrep',
    Difftastic: 'difftastic',
    Bash: 'bash',
    ListSlashCommands: 'listSlashCommands',
    ListSkills: 'listSkills',
    ListCodexModels: 'listCodexModels',
    GetCodexSubscriptionLimits: 'getCodexSubscriptionLimits',
    ForkCodexSideSession: 'forkCodexSideSession',
    ListCursorModels: 'listCursorModels',
    ListPiModels: 'listPiModels',
    ListOpencodeModels: 'listOpencodeModels',
    ListOpencodeModelsForCwd: 'listOpencodeModelsForCwd',
    ListOpencodeReasoningEffortOptions: 'listOpencodeReasoningEffortOptions',
    LocalPreviewCheck: 'localPreview.check',
    LocalPreviewHttpRequest: 'localPreview.httpRequest',
    OpenVikingStatus: 'openViking.status',
    OpenVikingListContext: 'openViking.listContext',
    OpenVikingReadContext: 'openViking.readContext'
} as const

export type RpcMethod = typeof RPC_METHODS[keyof typeof RPC_METHODS]
